# Axis-Angle Representations of 3D Rotations
### Chris Tralie

## Euler's Rotation Theorem


In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

In [2]:
R = np.array([[0.84, -0.49, -0.23],
              [0.18,  0.66, -0.73],
              [0.51,  0.57,  0.64]])

In [3]:
w, v = linalg.eig(R)
a = np.real(v[:, 0])
print(a)
print(R.dot(a))

[-0.793643    0.45216306 -0.4070373 ]
[-0.79460143  0.45270911 -0.40752886]


Euler's Rotation Theorem: For a given 3D rotation matrix $R$, there exists a vector $\vec{a}$ so that $R\vec{a} = \vec{a}$.  In other words, there is exactly one vector that stays fixed when we apply the rotation matrix

In [10]:
u = [1, 0, 0]
v = R.dot(u)
u = u - a*np.sum(u*a) # perp projection of u
u = u/np.sqrt(np.sum(u**2))
v = v - a*np.sum(v*a) # perp projection of v
v = v/np.sqrt(np.sum(v**2))
theta = -np.arccos(np.sum(u*v)) ## We need to be careful to check the sign of theta here!
## This example ended up being negative, but it's not always so
print(theta)

5.3187805777661605


## Rodrigues' Rotation Formula

<img src = "RodriguesDeriv.svg">


In [ ]:
## Here is some javascript code to do this
/**
 * Rotate a vector around an axis by a particular angle
 * 
 * @param {vec3} v Vector to rotate
 * @param {vec3} axis Axis around which to rotate
 * @param {float} theta Angle, in radians, to rotate
 * @returns vec3: Result of the rotation
 */
function rotateAxisAngle(v, axis, theta) {
    let vproja = proj(v, axis);
    let c = vec3.sub(vec3.create(), v, vproja);
    let s = vec3.cross(vec3.create(), axis, c);
    let vrot = vec3.scaleAndAdd(vec3.create(), vproja, c, Math.cos(theta));
    vrot = vec3.scaleAndAdd(vrot, vrot, s, Math.sin(theta));
    return vrot;
}

## Matrix Form of Axis/Angle

We can convert Rodrigues' rotation formula into this form:

### $\vec{v_{\text{rot}}} = \vec{v} + (1 - \cos \theta) (\vec{a} \times (\vec{a} \times \vec{v})) + \sin \theta (\vec{a} \times \vec{v}) $

Then, we make the observation that this cross product can be written as a matrix

### $ \vec{a} \times \vec{x} = A \vec{x}$

### $\vec{a} = (a_x, a_y, a_z)$

### $ A = \left[ \begin{array}{ccc} 0 & -a_z & a_y \\ a_z & 0 & -a_x \\ -a_y & a_x & 0   \end{array} \right]$

if we do some substitutions, we can eventually arrive at an equation to convert the axis/angle into a 3D rotation matrix

### $\vec{v_{\text{rot}}} = I\vec{v} + (1 - \cos \theta) (A A)\vec{v} + (\sin \theta A) \vec{v} $

### $R = I + (1 - \cos \theta) (A A) + \sin \theta (A)  $

In [11]:
A = np.array([[0, -a[2], a[1]], [a[2], 0, -a[0]], [-a[1], a[0], 0]])

R2 = np.eye(3) + (1-np.cos(theta))*(A.dot(A)) + np.sin(theta)*A
print(R2)

[[ 0.84080901 -0.48880833 -0.2326083 ]
 [ 0.18012476  0.65783943 -0.73130183]
 [ 0.51048534  0.57298665  0.6411638 ]]


In [12]:
print(R)

[[ 0.84 -0.49 -0.23]
 [ 0.18  0.66 -0.73]
 [ 0.51  0.57  0.64]]
